//Output in [{"ITEM_ID":248},{"ITEM_ID":205}]
BEGIN
  SELECT JSON_ARRAYAGG(
           JSON_OBJECT('ITEM_ID' VALUE ITEM_ID)
         )
    INTO :P174_PRODUCT_JSON
    FROM AB_ITEMS_MASTER
   WHERE VENDOR_NAME_ID = :P174_SR_IDS;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    :P174_PRODUCT_JSON := '[]';
END;
