//Output will be 123,45,121,87
BEGIN
  SELECT LISTAGG(ITEM_ID, ',') 
    INTO :P174_PRODUCT_IDS
    FROM AB_ITEMS_MASTER
   WHERE VENDOR_NAME_ID = :P174_SR_IDS;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    :P174_PRODUCT_IDS:= '';
END;
